import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="flex flex-col ">
    
         <nav className="text-white sm:p-2 md:p-4 flex justify-between items-center z-50 relative sm:text-sx" style={{background:"#0d2630"}}>
         <div className={`flex items-center lg:text-4xl sm:text-xs font-bold`}>
                <Image src="/assets/logo.png" alt="Logo" width={200} height={90} className="mr-2" sizes="(max-width: 600px) 30px" /> 
        </div>
      <div>
        <Link href="/books" className="px-2 md:px-4 ">RAN</Link>
        <Link href="/projects" className="px-2 md:px-4 ">GenAI</Link>
        <Link href="/events" className="px-2 md:px-4 ">mmWave</Link>
        <Link href="/publications" className="px-2 md:px-4">About</Link>
      </div>
    </nav>
    <div>
        {children}
     </div>        
    { //<footer className="bg-gray-900 text-white text-center p-4" style={{background:"#0d2630"}}>
       // © {new Date().getFullYear()} SPRINT Lab. All Rights Reserved.
      //</footer>
}
      </div>
      </body>
   

    </html>
  );
}
